const data = [
  { eng: "Apple", mar: "सफरचंद" },
  { eng: "Water", mar: "पाणी" },
  { eng: "Book", mar: "पुस्तक" },
  { eng: "Sun", mar: "सूर्य" } 
,
  { eng: "Angry", mar: "रागावलेला" },
  { eng: "Smile", mar: "हसू" },
  { eng: "Laugh", mar: "हसणे" },
  { eng: "Cry", mar: "रडणे" },
  { eng: "Sleep", mar: "झोप" },
  { eng: "Wake", mar: "जागे होणे" },
  { eng: "Sit", mar: "बसणे" },
  { eng: "Stand", mar: "उभे राहणे" },
  { eng: "Turn", mar: "वळणे" },
  { eng: "Look", mar: "पाहणे" },
  { eng: "See", mar: "दिसणे" },
  { eng: "Watch", mar: "पाहणे" },
  { eng: "Hear", mar: "ऐकू येणे" },
  { eng: "Listen", mar: "ऐकणे" },
  { eng: "Touch", mar: "स्पर्श करणे" },
  { eng: "Feel", mar: "जाणवणे" },
  { eng: "Taste", mar: "चव घेणे" },
  { eng: "Smell", mar: "वास घेणे" },
  { eng: "Hold", mar: "धरून ठेवणे" },
  { eng: "Drop", mar: "सोडणे" },
  { eng: "Pick", mar: "उचलणे" },
  { eng: "Throw", mar: "फेकणे" },
  { eng: "Catch", mar: "पकडणे" },
  { eng: "Push", mar: "ढकलणे" },
  { eng: "Pull", mar: "ओढणे" },
  { eng: "Give", mar: "देणे" },
  { eng: "Take", mar: "घेणे" },
  { eng: "Bring", mar: "आणणे" },
  { eng: "Send", mar: "पाठवणे" },
  { eng: "Call", mar: "बोलावणे" },
  { eng: "Meet", mar: "भेटणे" },
  { eng: "Help", mar: "मदत करणे" },
  { eng: "Work", mar: "काम" },
  { eng: "Rest", mar: "विश्रांती" },
  { eng: "Play", mar: "खेळणे" },
  { eng: "Study", mar: "अभ्यास करणे" },
  { eng: "Teach", mar: "शिकवणे" },
  { eng: "Learn", mar: "शिकणे" },
  { eng: "Ask", mar: "विचारणे" },
  { eng: "Answer", mar: "उत्तर देणे" },
  { eng: "Think", mar: "विचार करणे" },
  { eng: "Know", mar: "माहित असणे" },
  { eng: "Remember", mar: "आठवणे" },
  { eng: "Forget", mar: "विसरणे" },
  { eng: "Try", mar: "प्रयत्न करणे" },
  { eng: "Win", mar: "जिंकणे" },
  { eng: "Lose", mar: "हरणे" },
  { eng: "Start", mar: "सुरू करणे" },
  { eng: "Stop", mar: "थांबवणे" },
  { eng: "Open", mar: "उघडणे" },
  { eng: "Close", mar: "बंद करणे" },
  { eng: "Enter", mar: "आत जाणे" },
  { eng: "Exit", mar: "बाहेर जाणे" },
  { eng: "Buy", mar: "खरेदी करणे" },
  { eng: "Sell", mar: "विकणे" },
  { eng: "Pay", mar: "पैसे देणे" },
  { eng: "Save", mar: "वाचवणे" },
  { eng: "Spend", mar: "खर्च करणे" },
  { eng: "Eat", mar: "खाणे" },
  { eng: "Drink", mar: "पिणे" },
  { eng: "Cook", mar: "स्वयंपाक करणे" },
  { eng: "Clean", mar: "स्वच्छ करणे" },
  { eng: "Wash", mar: "धुणे" },
  { eng: "Dry", mar: "वाळवणे" },
  { eng: "Wear", mar: "घालणे" },
  { eng: "Remove", mar: "काढणे" },
  { eng: "Carry", mar: "उचलून नेणे" },
  { eng: "Travel", mar: "प्रवास करणे" },
  { eng: "Visit", mar: "भेट देणे" },
  { eng: "Stay", mar: "राहणे" },
  { eng: "Live", mar: "राहणे" },
  { eng: "Build", mar: "बांधणे" },
  { eng: "Break", mar: "तोडणे" },
  { eng: "Fix", mar: "दुरुस्त करणे" },
  { eng: "Cut", mar: "कापणे" },
  { eng: "Grow", mar: "वाढणे" },
  { eng: "Make", mar: "बनवणे" },
  { eng: "Create", mar: "निर्माण करणे" },
  { eng: "Use", mar: "वापरणे" },
  { eng: "Need", mar: "गरज असणे" },
  { eng: "Want", mar: "हवे असणे" },
  { eng: "Like", mar: "आवडणे" },
  { eng: "Love", mar: "प्रेम करणे" },
  { eng: "Hate", mar: "द्वेष करणे" },
  { eng: "Enjoy", mar: "आनंद घेणे" },
  { eng: "Share", mar: "वाटणे" },
  { eng: "Keep", mar: "ठेवणे" },
  { eng: "Lose", mar: "गमावणे" },
  { eng: "Find", mar: "शोधणे" },
  { eng: "Show", mar: "दाखवणे" },
  { eng: "Hide", mar: "लपवणे" },
  { eng: "Wait", mar: "थांबणे" },
  { eng: "Hurry", mar: "घाई करणे" }  
  ,
  { eng: "Abandon", mar: "त्याग करणे" },
  { eng: "Ability", mar: "क्षमता" },
  { eng: "Absorb", mar: "शोषून घेणे" },
  { eng: "Abstract", mar: "सारगर्भित" },
  { eng: "Accumulate", mar: "साठवणे" },
  { eng: "Accuse", mar: "आरोप करणे" },
  { eng: "Acquire", mar: "मिळवणे" },
  { eng: "Adaptation", mar: "अनुकूलन" },
  { eng: "Adequate", mar: "पुरेसा" },
  { eng: "Adjacent", mar: "शेजारील" },
  { eng: "Administer", mar: "प्रशासन करणे" },
  { eng: "Advocate", mar: "समर्थन करणे" },
  { eng: "Aggregate", mar: "एकूण" },
  { eng: "Allocate", mar: "वाटप करणे" },
  { eng: "Alter", mar: "बदल करणे" },
  { eng: "Ambiguous", mar: "दुहेरी अर्थाचा" },
  { eng: "Amend", mar: "सुधारणा करणे" },
  { eng: "Analyze", mar: "विश्लेषण करणे" },
  { eng: "Anticipate", mar: "अपेक्षा करणे" },
  { eng: "Apparent", mar: "स्पष्ट" },
  { eng: "Appropriate", mar: "योग्य" },
  { eng: "Arbitrary", mar: "मनमानी" },
  { eng: "Aspect", mar: "पैलू" },
  { eng: "Assess", mar: "मूल्यमापन करणे" },
  { eng: "Assign", mar: "नेमणे" },
  { eng: "Assist", mar: "मदत करणे" },
  { eng: "Assume", mar: "गृहित धरणे" },
  { eng: "Assure", mar: "खात्री देणे" },
  { eng: "Attach", mar: "जोडणे" },
  { eng: "Attain", mar: "प्राप्त करणे" },
  { eng: "Attribute", mar: "गुणधर्म" },
  { eng: "Authorize", mar: "अधिकृत करणे" },
  { eng: "Aware", mar: "जाणकार" },
  { eng: "Benefit", mar: "फायदा" },
  { eng: "Bias", mar: "पूर्वग्रह" },
  { eng: "Bond", mar: "बंधन" },
  { eng: "Brief", mar: "संक्षिप्त" },
  { eng: "Capable", mar: "सक्षम" },
  { eng: "Cease", mar: "थांबवणे" },
  { eng: "Clarify", mar: "स्पष्ट करणे" },
  { eng: "Coherent", mar: "सुसंगत" },
  { eng: "Collapse", mar: "कोसळणे" },
  { eng: "Compile", mar: "संकलित करणे" },
  { eng: "Comprehensive", mar: "सर्वसमावेशक" },
  { eng: "Conceal", mar: "लपवणे" },
  { eng: "Concentrate", mar: "एकाग्र करणे" },
  { eng: "Conclude", mar: "निष्कर्ष काढणे" },
  { eng: "Conduct", mar: "वर्तन" },
  { eng: "Confirm", mar: "पुष्टी करणे" },
  { eng: "Conflict", mar: "संघर्ष" },
  { eng: "Conform", mar: "पालन करणे" },
  { eng: "Consent", mar: "संमती" },
  { eng: "Consistent", mar: "सातत्यपूर्ण" },
  { eng: "Constitute", mar: "घडवणे" },
  { eng: "Constraint", mar: "मर्यादा" },
  { eng: "Construct", mar: "बांधणी करणे" },
  { eng: "Consume", mar: "वापर करणे" },
  { eng: "Contemporary", mar: "समकालीन" },
  { eng: "Contradict", mar: "विरोध करणे" },
  { eng: "Contribute", mar: "योगदान देणे" },
  { eng: "Convert", mar: "रूपांतर करणे" },
  { eng: "Convince", mar: "पटवणे" },
  { eng: "Core", mar: "मुख्य भाग" },
  { eng: "Correspond", mar: "जुळणे" },
  { eng: "Criteria", mar: "निकष" },
  { eng: "Crucial", mar: "महत्त्वाचा" },
  { eng: "Cumulative", mar: "संचित" },
  { eng: "Debate", mar: "वादविवाद" },
  { eng: "Deduce", mar: "निष्कर्ष काढणे" },
  { eng: "Definite", mar: "निश्चित" },
  { eng: "Demonstrate", mar: "दर्शवणे" },
  { eng: "Deny", mar: "नकार देणे" },
  { eng: "Derive", mar: "उत्पन्न करणे" },
  { eng: "Detect", mar: "शोधणे" },
  { eng: "Deviate", mar: "वळणे" },
  { eng: "Differentiate", mar: "भेद करणे" },
  { eng: "Diminish", mar: "कमी करणे" },
  { eng: "Discrete", mar: "स्वतंत्र" },
  { eng: "Display", mar: "प्रदर्शन करणे" },
  { eng: "Distinguish", mar: "वेगळे ओळखणे" },
  { eng: "Distribute", mar: "वाटप करणे" },
  { eng: "Diverse", mar: "विविध" },
  { eng: "Document", mar: "दस्तऐवज" },
  { eng: "Domestic", mar: "घरगुती" },
  { eng: "Dominate", mar: "प्रभुत्व गाजवणे" },
  { eng: "Duration", mar: "कालावधी" },
  { eng: "Dynamic", mar: "गतिशील" },
  { eng: "Economy", mar: "अर्थव्यवस्था" },
  { eng: "Eliminate", mar: "काढून टाकणे" },
  { eng: "Emphasize", mar: "भर देणे" },
  { eng: "Enable", mar: "सक्षम करणे" },
  { eng: "Encounter", mar: "सामोरे जाणे" },
  { eng: "Enhance", mar: "वाढवणे" } 
  ,
  { eng: "Accurate", mar: "अचूक" },
  { eng: "Approximate", mar: "अंदाजे" },
  { eng: "Analyze", mar: "विश्लेषण करणे" },
  { eng: "Assess", mar: "मूल्यमापन करणे" },
  { eng: "Assume", mar: "गृहित धरणे" },
  { eng: "Benefit", mar: "फायदा" },
  { eng: "Conclude", mar: "निष्कर्ष काढणे" },
  { eng: "Consequence", mar: "परिणाम" },
  { eng: "Consider", mar: "विचार करणे" },
  { eng: "Consist", mar: "समाविष्ट असणे" },
  { eng: "Context", mar: "संदर्भ" },
  { eng: "Criteria", mar: "निकष" },
  { eng: "Data", mar: "माहिती" },
  { eng: "Define", mar: "परिभाषित करणे" },
  { eng: "Derive", mar: "उत्पन्न करणे" },
  { eng: "Distribute", mar: "वितरण करणे" },
  { eng: "Economical", mar: "किफायतशीर" },
  { eng: "Emphasize", mar: "भर देणे" },
  { eng: "Enable", mar: "सक्षम करणे" },
  { eng: "Environment", mar: "पर्यावरण" },
  { eng: "Establish", mar: "स्थापन करणे" },
  { eng: "Evaluate", mar: "मूल्यांकन करणे" },
  { eng: "Evidence", mar: "पुरावा" },
  { eng: "Factor", mar: "घटक" },
  { eng: "Formula", mar: "सूत्र" },
  { eng: "Function", mar: "कार्य" },
  { eng: "Generate", mar: "निर्माण करणे" },
  { eng: "Identify", mar: "ओळखणे" },
  { eng: "Impact", mar: "परिणाम" },
  { eng: "Indicate", mar: "सूचित करणे" },
  { eng: "Individual", mar: "व्यक्ती" },
  { eng: "Interpret", mar: "अर्थ लावणे" },
  { eng: "Involve", mar: "सामाविष्ट करणे" },
  { eng: "Issue", mar: "मुद्दा" },
  { eng: "Legal", mar: "कायदेशीर" },
  { eng: "Legislate", mar: "कायदे करणे" },
  { eng: "Major", mar: "मुख्य" },
  { eng: "Minor", mar: "लहान" },
  { eng: "Methodology", mar: "कार्यपद्धती" },
  { eng: "Modify", mar: "बदल करणे" },
  { eng: "Monitor", mar: "नियंत्रण ठेवणे" },
  { eng: "Normal", mar: "सामान्य" },
  { eng: "Obtain", mar: "मिळवणे" },
  { eng: "Participate", mar: "भाग घेणे" },
  { eng: "Percent", mar: "टक्के" },
  { eng: "Period", mar: "कालावधी" },
  { eng: "Policy", mar: "धोरण" },
  { eng: "Proceed", mar: "पुढे जाणे" },
  { eng: "Process", mar: "प्रक्रिया" },
  { eng: "Project", mar: "प्रकल्प" },
  { eng: "Proportion", mar: "प्रमाण" },
  { eng: "Publish", mar: "प्रकाशित करणे" },
  { eng: "React", mar: "प्रतिक्रिया देणे" },
  { eng: "Region", mar: "प्रदेश" },
  { eng: "Regulate", mar: "नियंत्रित करणे" },
  { eng: "Relevant", mar: "संबंधित" },
  { eng: "Require", mar: "आवश्यक असणे" },
  { eng: "Research", mar: "संशोधन" },
  { eng: "Respond", mar: "प्रतिक्रिया देणे" },
  { eng: "Role", mar: "भूमिका" },
  { eng: "Section", mar: "विभाग" },
  { eng: "Sector", mar: "क्षेत्र" },
  { eng: "Significant", mar: "महत्त्वपूर्ण" },
  { eng: "Similar", mar: "सारखा" },
  { eng: "Source", mar: "स्रोत" },
  { eng: "Specific", mar: "विशिष्ट" },
  { eng: "Structure", mar: "रचना" },
  { eng: "Theory", mar: "सिद्धांत" },
  { eng: "Transfer", mar: "हस्तांतरण" },
  { eng: "Trend", mar: "कल" },
  { eng: "Valid", mar: "वैध" },
  { eng: "Variable", mar: "चल" },
  { eng: "Volume", mar: "आयतन" },
  { eng: "Welfare", mar: "कल्याण" },
  { eng: "Access", mar: "प्रवेश" },
  { eng: "Adapt", mar: "जुळवून घेणे" },
  { eng: "Adequate", mar: "पुरेसा" },
  { eng: "Alternative", mar: "पर्याय" },
  { eng: "Approach", mar: "दृष्टिकोन" },
  { eng: "Aspect", mar: "पैलू" },
  { eng: "Category", mar: "वर्ग" },
  { eng: "Complex", mar: "जटिल" },
  { eng: "Component", mar: "घटक" },
  { eng: "Concept", mar: "संकल्पना" },
  { eng: "Conduct", mar: "वर्तन" },
  { eng: "Confirm", mar: "पुष्टी करणे" },
  { eng: "Construct", mar: "बांधणी करणे" },
  { eng: "Convert", mar: "रूपांतर करणे" },
  { eng: "Core", mar: "मुख्य भाग" },
  { eng: "Credit", mar: "श्रेय" },
  { eng: "Culture", mar: "संस्कृती" },
  { eng: "Debate", mar: "वादविवाद" },
  { eng: "Device", mar: "साधन" },
  { eng: "Document", mar: "दस्तऐवज" },
  { eng: "Element", mar: "घटक" },
  { eng: "Equate", mar: "समान करणे" } 
  ,
  { eng: "Authority", mar: "सत्ता" },
  { eng: "Administration", mar: "प्रशासन" },
  { eng: "Policy", mar: "धोरण" },
  { eng: "Regulation", mar: "नियमावली" },
  { eng: "Agreement", mar: "करार" },
  { eng: "Contract", mar: "करारपत्र" },
  { eng: "Permission", mar: "परवानगी" },
  { eng: "Restriction", mar: "मर्यादा" },
  { eng: "Limit", mar: "सीमा" },
  { eng: "Boundary", mar: "सीमारेषा" },
  { eng: "Region", mar: "प्रदेश" },
  { eng: "Area", mar: "क्षेत्र" },
  { eng: "Location", mar: "ठिकाण" },
  { eng: "Position", mar: "स्थान" },
  { eng: "Direction", mar: "दिशा" },
  { eng: "Distance", mar: "अंतर" },
  { eng: "Journey", mar: "प्रवास" },
  { eng: "Travel", mar: "प्रवास करणे" },
  { eng: "Transport", mar: "वाहतूक" },
  { eng: "Vehicle", mar: "वाहन" },
  { eng: "Driver", mar: "चालक" },
  { eng: "Passenger", mar: "प्रवासी" },
  { eng: "Ticket", mar: "तिकीट" },
  { eng: "Station", mar: "स्थानक" },
  { eng: "Platform", mar: "फ्लॅटफॉर्म" },
  { eng: "Airport", mar: "विमानतळ" },
  { eng: "Flight", mar: "उड्डाण" },
  { eng: "Schedule", mar: "वेळापत्रक" },
  { eng: "Delay", mar: "उशीर" },
  { eng: "Cancel", mar: "रद्द करणे" },
  { eng: "Reserve", mar: "आरक्षित करणे" },
  { eng: "Book", mar: "बुक करणे" },
  { eng: "Payment", mar: "देयक" },
  { eng: "Price", mar: "किंमत" },
  { eng: "Cost", mar: "खर्च" },
  { eng: "Value", mar: "मूल्य" },
  { eng: "Profit", mar: "नफा" },
  { eng: "Loss", mar: "तोटा" },
  { eng: "Income", mar: "उत्पन्न" },
  { eng: "Expense", mar: "खर्च" },
  { eng: "Budget", mar: "अंदाजपत्रक" },
  { eng: "Saving", mar: "बचत" },
  { eng: "Investment", mar: "गुंतवणूक" },
  { eng: "Bank", mar: "बँक" },
  { eng: "Account", mar: "खाते" },
  { eng: "Deposit", mar: "ठेव" },
  { eng: "Withdraw", mar: "काढणे" },
  { eng: "Loan", mar: "कर्ज" },
  { eng: "Interest", mar: "व्याज" },
  { eng: "Market", mar: "बाजार" },
  { eng: "Demand", mar: "मागणी" },
  { eng: "Supply", mar: "पुरवठा" },
  { eng: "Production", mar: "उत्पादन" },
  { eng: "Distribution", mar: "वितरण" },
  { eng: "Consumption", mar: "वापर" },
  { eng: "Resource", mar: "संसाधन" },
  { eng: "Material", mar: "साहित्य" },
  { eng: "Product", mar: "उत्पादन" },
  { eng: "Quality", mar: "गुणवत्ता" },
  { eng: "Quantity", mar: "प्रमाण" },
  { eng: "Standard", mar: "मानक" },
  { eng: "Measure", mar: "मोजमाप" },
  { eng: "Unit", mar: "एकक" },
  { eng: "Scale", mar: "प्रमाण" },
  { eng: "Level", mar: "पातळी" },
  { eng: "Stage", mar: "टप्पा" },
  { eng: "Process", mar: "प्रक्रिया" },
  { eng: "Operation", mar: "कारवाई" },
  { eng: "Function", mar: "कार्य" },
  { eng: "Role", mar: "भूमिका" },
  { eng: "Responsibility", mar: "जबाबदारी" },
  { eng: "Performance", mar: "कामगिरी" },
  { eng: "Efficiency", mar: "कार्यक्षमता" },
  { eng: "Effectiveness", mar: "प्रभावीपणा" },
  { eng: "Improvement", mar: "सुधारणा" },
  { eng: "Development", mar: "विकास" },
  { eng: "Innovation", mar: "नवकल्पना" },
  { eng: "Technology", mar: "तंत्रज्ञान" },
  { eng: "Device", mar: "साधन" },
  { eng: "Machine", mar: "यंत्र" },
  { eng: "Tool", mar: "साधन" },
  { eng: "Equipment", mar: "उपकरणे" },
  { eng: "System", mar: "प्रणाली" },
  { eng: "Network", mar: "जाळे" },
  { eng: "Connection", mar: "जोडणी" },
  { eng: "Signal", mar: "संकेत" },
  { eng: "Data", mar: "माहिती" },
  { eng: "Information", mar: "माहिती" },
  { eng: "Knowledge", mar: "ज्ञान" },
  { eng: "Communication", mar: "संपर्क" },
  { eng: "Message", mar: "संदेश" },
  { eng: "Media", mar: "माध्यम" },
  { eng: "News", mar: "बातम्या" },
  { eng: "Report", mar: "अहवाल" } 
  ,
  { eng: "Ability", mar: "क्षमता" },
  { eng: "Advantage", mar: "फायदा" },
  { eng: "Disadvantage", mar: "तोटा" },
  { eng: "Balance", mar: "संतुलन" },
  { eng: "Change", mar: "बदल" },
  { eng: "Development", mar: "विकास" },
  { eng: "Growth", mar: "वाढ" },
  { eng: "Improvement", mar: "सुधारणा" },
  { eng: "Increase", mar: "वाढ" },
  { eng: "Decrease", mar: "कमी" },
  { eng: "Reduce", mar: "कमी करणे" },
  { eng: "Expand", mar: "वाढवणे" },
  { eng: "Control", mar: "नियंत्रण" },
  { eng: "Manage", mar: "व्यवस्थापन करणे" },
  { eng: "Organize", mar: "संघटित करणे" },
  { eng: "Create", mar: "निर्माण करणे" },
  { eng: "Destroy", mar: "नष्ट करणे" },
  { eng: "Protect", mar: "संरक्षण करणे" },
  { eng: "Attack", mar: "हल्ला करणे" },
  { eng: "Defend", mar: "बचाव करणे" },
  { eng: "Build", mar: "उभारणे" },
  { eng: "Develop", mar: "विकसित करणे" },
  { eng: "Achieve", mar: "साध्य करणे" },
  { eng: "Complete", mar: "पूर्ण करणे" },
  { eng: "Finish", mar: "समाप्त करणे" },
  { eng: "Begin", mar: "सुरुवात करणे" },
  { eng: "Continue", mar: "सुरू ठेवणे" },
  { eng: "Improve", mar: "सुधारणे" },
  { eng: "Progress", mar: "प्रगती" },
  { eng: "Result", mar: "निकाल" },
  { eng: "Effect", mar: "परिणाम" },
  { eng: "Cause", mar: "कारण" },
  { eng: "Impact", mar: "परिणाम" },
  { eng: "Situation", mar: "परिस्थिती" },
  { eng: "Condition", mar: "स्थिती" },
  { eng: "Opportunity", mar: "संधी" },
  { eng: "Challenge", mar: "आव्हान" },
  { eng: "Risk", mar: "धोका" },
  { eng: "Safety", mar: "सुरक्षितता" },
  { eng: "Danger", mar: "धोका" },
  { eng: "Emergency", mar: "आपत्कालीन स्थिती" },
  { eng: "Service", mar: "सेवा" },
  { eng: "Support", mar: "मदत" },
  { eng: "System", mar: "प्रणाली" },
  { eng: "Process", mar: "प्रक्रिया" },
  { eng: "Method", mar: "पद्धत" },
  { eng: "Technique", mar: "तंत्र" },
  { eng: "Strategy", mar: "रणनीती" },
  { eng: "Plan", mar: "योजना" },
  { eng: "Design", mar: "रचना" },
  { eng: "Structure", mar: "संरचना" },
  { eng: "Model", mar: "मॉडेल" },
  { eng: "Example", mar: "उदाहरण" },
  { eng: "Case", mar: "प्रकरण" },
  { eng: "Detail", mar: "तपशील" },
  { eng: "Summary", mar: "सारांश" },
  { eng: "Report", mar: "अहवाल" },
  { eng: "Analysis", mar: "विश्लेषण" },
  { eng: "Research", mar: "संशोधन" },
  { eng: "Study", mar: "अभ्यास" },
  { eng: "Test", mar: "चाचणी" },
  { eng: "Check", mar: "तपासणी" },
  { eng: "Measure", mar: "मोजमाप" },
  { eng: "Compare", mar: "तुलना करणे" },
  { eng: "Connect", mar: "जोडणे" },
  { eng: "Separate", mar: "वेगळे करणे" },
  { eng: "Combine", mar: "एकत्र करणे" },
  { eng: "Divide", mar: "विभागणे" },
  { eng: "Add", mar: "जोडणे" },
  { eng: "Subtract", mar: "वजाबाकी करणे" },
  { eng: "Multiply", mar: "गुणाकार करणे" },
  { eng: "Divide", mar: "भागाकार करणे" },
  { eng: "Count", mar: "मोजणे" },
  { eng: "Calculate", mar: "गणना करणे" },
  { eng: "Estimate", mar: "अंदाज" },
  { eng: "Predict", mar: "भाकीत करणे" },
  { eng: "Explain", mar: "स्पष्ट करणे" },
  { eng: "Describe", mar: "वर्णन करणे" },
  { eng: "Define", mar: "परिभाषित करणे" },
  { eng: "Identify", mar: "ओळखणे" },
  { eng: "Recognize", mar: "ओळख पटवणे" },
  { eng: "Observe", mar: "निरीक्षण करणे" },
  { eng: "Notice", mar: "लक्ष देणे" },
  { eng: "Focus", mar: "लक्ष केंद्रित करणे" },
  { eng: "Attention", mar: "लक्ष" },
  { eng: "Concentration", mar: "एकाग्रता" },
  { eng: "Memory", mar: "स्मरणशक्ती" },
  { eng: "Learning", mar: "शिकणे" },
  { eng: "Education", mar: "शिक्षण" },
  { eng: "Knowledge", mar: "ज्ञान" },
  { eng: "Skill", mar: "कौशल्य" },
  { eng: "Experience", mar: "अनुभव" },
  { eng: "Performance", mar: "कामगिरी" } 
  ,
  { eng: "Science", mar: "विज्ञान" },
  { eng: "Physics", mar: "भौतिकशास्त्र" },
  { eng: "Chemistry", mar: "रसायनशास्त्र" },
  { eng: "Biology", mar: "जीवशास्त्र" },
  { eng: "Mathematics", mar: "गणित" },
  { eng: "History", mar: "इतिहास" },
  { eng: "Geography", mar: "भूगोल" },
  { eng: "Civics", mar: "नागरिकशास्त्र" },
  { eng: "Economics", mar: "अर्थशास्त्र" },
  { eng: "Environment", mar: "पर्यावरण" },
  { eng: "Energy", mar: "ऊर्जा" },
  { eng: "Force", mar: "बल" },
  { eng: "Motion", mar: "गती" },
  { eng: "Speed", mar: "वेग" },
  { eng: "Velocity", mar: "वेग (दिशेसह)" },
  { eng: "Acceleration", mar: "त्वरण" },
  { eng: "Mass", mar: "वजन" },
  { eng: "Weight", mar: "भार" },
  { eng: "Gravity", mar: "गुरुत्वाकर्षण" },
  { eng: "Friction", mar: "घर्षण" },
  { eng: "Work", mar: "कार्य" },
  { eng: "Power", mar: "शक्ती" },
  { eng: "Heat", mar: "उष्णता" },
  { eng: "Temperature", mar: "तापमान" },
  { eng: "Light", mar: "प्रकाश" },
  { eng: "Sound", mar: "ध्वनी" },
  { eng: "Electricity", mar: "विद्युत" },
  { eng: "Magnetism", mar: "चुंबकत्व" },
  { eng: "Atom", mar: "अणू" },
  { eng: "Molecule", mar: "अणुकण" },
  { eng: "Element", mar: "मूलद्रव्य" },
  { eng: "Compound", mar: "संयोग" },
  { eng: "Reaction", mar: "प्रतिक्रिया" },
  { eng: "Acid", mar: "आम्ल" },
  { eng: "Base", mar: "क्षार" },
  { eng: "Salt", mar: "मीठ" },
  { eng: "Cell", mar: "पेशी" },
  { eng: "Tissue", mar: "ऊतक" },
  { eng: "Organ", mar: "अवयव" },
  { eng: "System", mar: "प्रणाली" },
  { eng: "Digestion", mar: "पचन" },
  { eng: "Respiration", mar: "श्वसन" },
  { eng: "Circulation", mar: "रक्ताभिसरण" },
  { eng: "Excretion", mar: "उत्सर्जन" },
  { eng: "Reproduction", mar: "प्रजनन" },
  { eng: "Photosynthesis", mar: "प्रकाशसंश्लेषण" },
  { eng: "Plant", mar: "वनस्पती" },
  { eng: "Animal", mar: "प्राणी" },
  { eng: "Human", mar: "मानव" },
  { eng: "Population", mar: "लोकसंख्या" },
  { eng: "Society", mar: "समाज" },
  { eng: "Culture", mar: "संस्कृती" },
  { eng: "Tradition", mar: "परंपरा" },
  { eng: "Religion", mar: "धर्म" },
  { eng: "Government", mar: "सरकार" },
  { eng: "Democracy", mar: "लोकशाही" },
  { eng: "Election", mar: "निवडणूक" },
  { eng: "Vote", mar: "मत" },
  { eng: "Citizen", mar: "नागरिक" },
  { eng: "Constitution", mar: "संविधान" },
  { eng: "Rights", mar: "अधिकार" },
  { eng: "Duties", mar: "कर्तव्ये" },
  { eng: "Justice", mar: "न्याय" },
  { eng: "Equality", mar: "समानता" },
  { eng: "Liberty", mar: "स्वातंत्र्य" },
  { eng: "Economy", mar: "अर्थव्यवस्था" },
  { eng: "Market", mar: "बाजार" },
  { eng: "Trade", mar: "व्यापार" },
  { eng: "Business", mar: "व्यवसाय" },
  { eng: "Industry", mar: "उद्योग" },
  { eng: "Agriculture", mar: "शेती" },
  { eng: "Farmer", mar: "शेतकरी" },
  { eng: "Crop", mar: "पीक" },
  { eng: "Irrigation", mar: "सिंचन" },
  { eng: "Transport", mar: "वाहतूक" },
  { eng: "Communication", mar: "संपर्क" },
  { eng: "Technology", mar: "तंत्रज्ञान" },
  { eng: "Computer", mar: "संगणक" },
  { eng: "Internet", mar: "इंटरनेट" },
  { eng: "Software", mar: "सॉफ्टवेअर" },
  { eng: "Hardware", mar: "हार्डवेअर" },
  { eng: "Program", mar: "कार्यक्रम" },
  { eng: "Code", mar: "संहिता" },
  { eng: "Data", mar: "माहिती" },
  { eng: "File", mar: "फाइल" },
  { eng: "Folder", mar: "फोल्डर" },
  { eng: "Network", mar: "जाळे" },
  { eng: "Security", mar: "सुरक्षा" },
  { eng: "Password", mar: "पासवर्ड" },
  { eng: "Login", mar: "प्रवेश" },
  { eng: "Logout", mar: "बाहेर पडणे" } 
  ,
  { eng: "Idea", mar: "कल्पना" },
  { eng: "Thought", mar: "विचार" },
  { eng: "Memory", mar: "आठवण" },
  { eng: "Dream", mar: "स्वप्न" },
  { eng: "Goal", mar: "ध्येय" },
  { eng: "Plan", mar: "योजना" },
  { eng: "Decision", mar: "निर्णय" },
  { eng: "Choice", mar: "निवड" },
  { eng: "Reason", mar: "कारण" },
  { eng: "Result", mar: "परिणाम" },
  { eng: "Success", mar: "यश" },
  { eng: "Failure", mar: "अपयश" },
  { eng: "Effort", mar: "प्रयत्न" },
  { eng: "Hardwork", mar: "कष्ट" },
  { eng: "Practice", mar: "सराव" },
  { eng: "Skill", mar: "कौशल्य" },
  { eng: "Talent", mar: "गुण" },
  { eng: "Knowledge", mar: "ज्ञान" },
  { eng: "Wisdom", mar: "शहाणपण" },
  { eng: "Experience", mar: "अनुभव" },
  { eng: "Truth", mar: "सत्य" },
  { eng: "Lie", mar: "खोटे" },
  { eng: "Fact", mar: "तथ्य" },
  { eng: "Belief", mar: "विश्वास" },
  { eng: "Faith", mar: "श्रद्धा" },
  { eng: "Trust", mar: "विश्वास" },
  { eng: "Respect", mar: "आदर" },
  { eng: "Love", mar: "प्रेम" },
  { eng: "Hate", mar: "द्वेष" },
  { eng: "Peace", mar: "शांती" },
  { eng: "War", mar: "युद्ध" },
  { eng: "Freedom", mar: "स्वातंत्र्य" },
  { eng: "Responsibility", mar: "जबाबदारी" },
  { eng: "Duty", mar: "कर्तव्य" },
  { eng: "Right", mar: "हक्क" },
  { eng: "Law", mar: "कायदा" },
  { eng: "Rule", mar: "नियम" },
  { eng: "Order", mar: "आदेश" },
  { eng: "Permission", mar: "परवानगी" },
  { eng: "Request", mar: "विनंती" },
  { eng: "Advice", mar: "सल्ला" },
  { eng: "Warning", mar: "इशारा" },
  { eng: "Help", mar: "मदत" },
  { eng: "Support", mar: "आधार" },
  { eng: "Care", mar: "काळजी" },
  { eng: "Health", mar: "आरोग्य" },
  { eng: "Disease", mar: "आजार" },
  { eng: "Medicine", mar: "औषध" },
  { eng: "Doctor", mar: "डॉक्टर" },
  { eng: "Hospital", mar: "रुग्णालय" },
  { eng: "School", mar: "शाळा" },
  { eng: "College", mar: "महाविद्यालय" },
  { eng: "Subject", mar: "विषय" },
  { eng: "Lesson", mar: "धडा" },
  { eng: "Chapter", mar: "प्रकरण" },
  { eng: "Exam", mar: "परीक्षा" },
  { eng: "Mark", mar: "गुण" },
  { eng: "Grade", mar: "श्रेणी" },
  { eng: "Pass", mar: "उत्तीर्ण" },
  { eng: "Fail", mar: "नापास" },
  { eng: "Question", mar: "प्रश्न" },
  { eng: "Answer", mar: "उत्तर" },
  { eng: "Problem", mar: "समस्या" },
  { eng: "Solution", mar: "उपाय" },
  { eng: "Example", mar: "उदाहरण" },
  { eng: "Explanation", mar: "स्पष्टीकरण" },
  { eng: "Information", mar: "माहिती" },
  { eng: "Message", mar: "संदेश" },
  { eng: "News", mar: "बातमी" },
  { eng: "Story", mar: "कथा" },
  { eng: "Poem", mar: "कविता" },
  { eng: "Language", mar: "भाषा" },
  { eng: "Word", mar: "शब्द" },
  { eng: "Sentence", mar: "वाक्य" },
  { eng: "Meaning", mar: "अर्थ" },
  { eng: "Translation", mar: "भाषांतर" },
  { eng: "Reading", mar: "वाचन" },
  { eng: "Writing", mar: "लेखन" },
  { eng: "Speaking", mar: "बोलणे" },
  { eng: "Listening", mar: "ऐकणे" },
  { eng: "Grammar", mar: "व्याकरण" },
  { eng: "Noun", mar: "नाम" },
  { eng: "Verb", mar: "क्रियापद" },
  { eng: "Adjective", mar: "विशेषण" },
  { eng: "Pronoun", mar: "सर्वनाम" },
  { eng: "Preposition", mar: "पूर्वप्रयोग" },
  { eng: "Conjunction", mar: "उभयान्वयी अव्यय" },
  { eng: "Interjection", mar: "उद्गारवाचक शब्द" },
  { eng: "Paragraph", mar: "परिच्छेद" },
  { eng: "Essay", mar: "निबंध" },
  { eng: "Letter", mar: "पत्र" },
  { eng: "Application", mar: "अर्ज" },
  { eng: "Notice", mar: "सूचना" },
  { eng: "Report", mar: "अहवाल" } 
  ,
  { eng: "Jump", mar: "उडी मारणे" },
  { eng: "Climb", mar: "चढणे" },
  { eng: "Swim", mar: "पोहोणे" },
  { eng: "Fly", mar: "उडणे" },
  { eng: "Drive", mar: "गाडी चालवणे" },
  { eng: "Cook", mar: "स्वयंपाक करणे" },
  { eng: "Wash", mar: "धुणे" },
  { eng: "Clean", mar: "स्वच्छ करणे" },
  { eng: "Build", mar: "बांधणे" },
  { eng: "Break", mar: "तोडणे" },
  { eng: "Fix", mar: "दुरुस्त करणे" },
  { eng: "Cut", mar: "कापणे" },
  { eng: "Draw", mar: "चित्र काढणे" },
  { eng: "Sing", mar: "गाणे गाणे" },
  { eng: "Dance", mar: "नाचणे" },
  { eng: "Laugh", mar: "हसणे" },
  { eng: "Cry", mar: "रडणे" },
  { eng: "Think", mar: "विचार करणे" },
  { eng: "Know", mar: "माहित असणे" },
  { eng: "Understand", mar: "समजणे" },
  { eng: "Learn", mar: "शिकणे" },
  { eng: "Teach", mar: "शिकवणे" },
  { eng: "Ask", mar: "विचारणे" },
  { eng: "Answer", mar: "उत्तर देणे" },
  { eng: "Help", mar: "मदत करणे" },
  { eng: "Give", mar: "देणे" },
  { eng: "Take", mar: "घेणे" },
  { eng: "Bring", mar: "आणणे" },
  { eng: "Send", mar: "पाठवणे" },
  { eng: "Receive", mar: "घेणे" },
  { eng: "Buy", mar: "खरेदी करणे" },
  { eng: "Sell", mar: "विकणे" },
  { eng: "Pay", mar: "पैसे देणे" },
  { eng: "Open", mar: "उघडणे" },
  { eng: "Close", mar: "बंद करणे" },
  { eng: "Start", mar: "सुरू करणे" },
  { eng: "Stop", mar: "थांबवणे" },
  { eng: "Win", mar: "जिंकणे" },
  { eng: "Lose", mar: "हरणे" },
  { eng: "Find", mar: "सापडणे" },
  { eng: "Lose", mar: "गमावणे" },
  { eng: "Keep", mar: "ठेवणे" },
  { eng: "Hold", mar: "धरून ठेवणे" },
  { eng: "Push", mar: "ढकलणे" },
  { eng: "Pull", mar: "ओढणे" },
  { eng: "Throw", mar: "फेकणे" },
  { eng: "Catch", mar: "पकडणे" },
  { eng: "Carry", mar: "उचलून नेणे" },
  { eng: "Wear", mar: "घालणे" },
  { eng: "Remove", mar: "काढणे" },
  { eng: "Light", mar: "हलका" },
  { eng: "Heavy", mar: "जड" },
  { eng: "Tall", mar: "उंच" },
  { eng: "Short", mar: "ठेंगणा" },
  { eng: "Long", mar: "लांब" },
  { eng: "Wide", mar: "रुंद" },
  { eng: "Narrow", mar: "अरुंद" },
  { eng: "Thick", mar: "जाड" },
  { eng: "Thin", mar: "पातळ" },
  { eng: "Strong", mar: "मजबूत" },
  { eng: "Weak", mar: "कमकुवत" },
  { eng: "Bright", mar: "तेजस्वी" },
  { eng: "Dark", mar: "अंधार" },
  { eng: "Early", mar: "लवकर" },
  { eng: "Late", mar: "उशिरा" },
  { eng: "Near", mar: "जवळ" },
  { eng: "Far", mar: "दूर" },
  { eng: "Inside", mar: "आत" },
  { eng: "Outside", mar: "बाहेर" },
  { eng: "Above", mar: "वर" },
  { eng: "Below", mar: "खाली" },
  { eng: "Before", mar: "आधी" },
  { eng: "After", mar: "नंतर" },
  { eng: "Always", mar: "नेहमी" },
  { eng: "Never", mar: "कधीच नाही" },
  { eng: "Sometimes", mar: "कधी कधी" },
  { eng: "Often", mar: "बर्‍याचदा" },
  { eng: "Together", mar: "एकत्र" },
  { eng: "Alone", mar: "एकटा" },
  { eng: "Same", mar: "सारखा" },
  { eng: "Different", mar: "वेगळा" },
  { eng: "Right", mar: "बरोबर" },
  { eng: "Wrong", mar: "चुकीचा" },
  { eng: "Easy", mar: "सोपे" },
  { eng: "Difficult", mar: "कठीण" },
  { eng: "Important", mar: "महत्त्वाचे" },
  { eng: "Famous", mar: "प्रसिद्ध" },
  { eng: "Beautiful", mar: "सुंदर" },
  { eng: "Ugly", mar: "कुरूप" },
  { eng: "Rich", mar: "श्रीमंत" },
  { eng: "Poor", mar: "गरीब" },
  { eng: "Kind", mar: "दयाळू" },
  { eng: "Cruel", mar: "क्रूर" },
  { eng: "Brave", mar: "धाडसी" },
  { eng: "Coward", mar: "भित्रा" },
  { eng: "Honest", mar: "प्रामाणिक" },
  { eng: "Dishonest", mar: "बेईमान" } ,
  { eng: "Apple", mar: "सफरचंद" },
  { eng: "Ball", mar: "चेंडू" },
  { eng: "Cat", mar: "मांजर" },
  { eng: "Dog", mar: "कुत्रा" },
  { eng: "Sun", mar: "सूर्य" },
  { eng: "Moon", mar: "चंद्र" },
  { eng: "Star", mar: "तारा" },
  { eng: "Water", mar: "पाणी" },
  { eng: "Milk", mar: "दूध" },
  { eng: "Book", mar: "पुस्तक" },
  { eng: "Pen", mar: "पेन" },
  { eng: "Pencil", mar: "पेन्सिल" },
  { eng: "Table", mar: "टेबल" },
  { eng: "Chair", mar: "खुर्ची" },
  { eng: "Bag", mar: "पिशवी" },
  { eng: "School", mar: "शाळा" },
  { eng: "Teacher", mar: "शिक्षक" },
  { eng: "Student", mar: "विद्यार्थी" },
  { eng: "Boy", mar: "मुलगा" },
  { eng: "Girl", mar: "मुलगी" },
  { eng: "Man", mar: "माणूस" },
  { eng: "Woman", mar: "स्त्री" },
  { eng: "Mother", mar: "आई" },
  { eng: "Father", mar: "वडील" },
  { eng: "Brother", mar: "भाऊ" },
  { eng: "Sister", mar: "बहीण" },
  { eng: "Food", mar: "अन्न" },
  { eng: "Rice", mar: "भात" },
  { eng: "Bread", mar: "भाकरी" },
  { eng: "Sugar", mar: "साखर" },
  { eng: "Salt", mar: "मीठ" },
  { eng: "Tree", mar: "झाड" },
  { eng: "Leaf", mar: "पान" },
  { eng: "Flower", mar: "फूल" },
  { eng: "Fruit", mar: "फळ" },
  { eng: "Road", mar: "रस्ता" },
  { eng: "House", mar: "घर" },
  { eng: "Door", mar: "दरवाजा" },
  { eng: "Window", mar: "खिडकी" },
  { eng: "Sky", mar: "आकाश" },
  { eng: "Earth", mar: "पृथ्वी" },
  { eng: "Fire", mar: "आग" },
  { eng: "Air", mar: "हवा" },
  { eng: "Rain", mar: "पाऊस" },
  { eng: "River", mar: "नदी" },
  { eng: "Mountain", mar: "डोंगर" },
  { eng: "Sea", mar: "समुद्र" },
  { eng: "Fish", mar: "मासा" },
  { eng: "Bird", mar: "पक्षी" },
  { eng: "Cow", mar: "गाय" },
  { eng: "Goat", mar: "शेळी" },
  { eng: "Horse", mar: "घोडा" },
  { eng: "Lion", mar: "सिंह" },
  { eng: "Tiger", mar: "वाघ" },
  { eng: "Elephant", mar: "हत्ती" },
  { eng: "Monkey", mar: "माकड" },
  { eng: "Snake", mar: "साप" },
  { eng: "Egg", mar: "अंडे" },
  { eng: "Butter", mar: "लोणी" },
  { eng: "Oil", mar: "तेल" },
  { eng: "Clothes", mar: "कपडे" },
  { eng: "Shirt", mar: "शर्ट" },
  { eng: "Pant", mar: "पँट" },
  { eng: "Shoes", mar: "बूट" },
  { eng: "Cap", mar: "टोपी" },
  { eng: "Clock", mar: "घड्याळ" },
  { eng: "Time", mar: "वेळ" },
  { eng: "Day", mar: "दिवस" },
  { eng: "Night", mar: "रात्र" },
  { eng: "Morning", mar: "सकाळ" },
  { eng: "Evening", mar: "संध्याकाळ" },
  { eng: "Friend", mar: "मित्र" },
  { eng: "Game", mar: "खेळ" },
  { eng: "Play", mar: "खेळणे" },
  { eng: "Run", mar: "पळणे" },
  { eng: "Walk", mar: "चालणे" },
  { eng: "Eat", mar: "खाणे" },
  { eng: "Drink", mar: "पिणे" },
  { eng: "Read", mar: "वाचणे" },
  { eng: "Write", mar: "लिहिणे" },
  { eng: "Speak", mar: "बोलणे" },
  { eng: "Listen", mar: "ऐकणे" },
  { eng: "Open", mar: "उघडणे" },
  { eng: "Close", mar: "बंद करणे" },
  { eng: "Big", mar: "मोठा" },
  { eng: "Small", mar: "लहान" },
  { eng: "Hot", mar: "गरम" },
  { eng: "Cold", mar: "थंड" },
  { eng: "Good", mar: "चांगला" },
  { eng: "Bad", mar: "वाईट" },
  { eng: "Happy", mar: "आनंदी" },
  { eng: "Sad", mar: "दुःखी" },
  { eng: "Fast", mar: "वेगवान" },
  { eng: "Slow", mar: "हळू" },
  { eng: "Clean", mar: "स्वच्छ" },
  { eng: "Dirty", mar: "घाण" },
  { eng: "Full", mar: "पूर्ण" },
  { eng: "Empty", mar: "रिकामे" } 
  ,
  { eng: "Happy", mar: "आनंदी" },
  { eng: "Sad", mar: "दुःखी" },
  { eng: "Tired", mar: "थकलेला" },
  { eng: "Hungry", mar: "भुकेला" },
  { eng: "Thirsty", mar: "तहानलेला" },
  { eng: "Busy", mar: "व्यस्त" },
  { eng: "Free", mar: "मोकळा" },
  { eng: "Early", mar: "लवकर" },
  { eng: "Late", mar: "उशिरा" },
  { eng: "Today", mar: "आज" },
  { eng: "Tomorrow", mar: "उद्या" },
  { eng: "Yesterday", mar: "काल" },
  { eng: "Now", mar: "आता" },
  { eng: "Then", mar: "तेव्हा" },
  { eng: "Always", mar: "नेहमी" },
  { eng: "Never", mar: "कधीच नाही" },
  { eng: "Sometimes", mar: "कधी कधी" },
  { eng: "Often", mar: "बर्‍याचदा" },
  { eng: "Here", mar: "इथे" },
  { eng: "There", mar: "तिथे" },
  { eng: "Everywhere", mar: "सर्वत्र" },
  { eng: "Somewhere", mar: "कुठेतरी" },
  { eng: "Anywhere", mar: "कुठेही" },
  { eng: "Near", mar: "जवळ" },
  { eng: "Far", mar: "दूर" },
  { eng: "Inside", mar: "आत" },
  { eng: "Outside", mar: "बाहेर" },
  { eng: "Up", mar: "वर" },
  { eng: "Down", mar: "खाली" },
  { eng: "Left", mar: "डावीकडे" },
  { eng: "Right", mar: "उजवीकडे" },
  { eng: "Front", mar: "समोर" },
  { eng: "Back", mar: "मागे" },
  { eng: "Before", mar: "आधी" },
  { eng: "After", mar: "नंतर" },
  { eng: "Again", mar: "पुन्हा" },
  { eng: "Together", mar: "एकत्र" },
  { eng: "Alone", mar: "एकटा" },
  { eng: "Same", mar: "सारखा" },
  { eng: "Different", mar: "वेगळा" },
  { eng: "More", mar: "जास्त" },
  { eng: "Less", mar: "कमी" },
  { eng: "Many", mar: "अनेक" },
  { eng: "Few", mar: "थोडे" },
  { eng: "All", mar: "सर्व" },
  { eng: "Some", mar: "काही" },
  { eng: "None", mar: "काहीही नाही" },
  { eng: "Each", mar: "प्रत्येक" },
  { eng: "Every", mar: "प्रत्येक" },
  { eng: "First", mar: "पहिला" },
  { eng: "Last", mar: "शेवटचा" },
  { eng: "Next", mar: "पुढचा" },
  { eng: "Old", mar: "जुना" },
  { eng: "New", mar: "नवीन" },
  { eng: "Young", mar: "तरुण" },
  { eng: "Easy", mar: "सोपे" },
  { eng: "Hard", mar: "कठीण" },
  { eng: "Strong", mar: "मजबूत" },
  { eng: "Weak", mar: "कमकुवत" },
  { eng: "Clean", mar: "स्वच्छ" },
  { eng: "Dirty", mar: "घाण" },
  { eng: "Full", mar: "पूर्ण" },
  { eng: "Empty", mar: "रिकामे" },
  { eng: "Fast", mar: "जलद" },
  { eng: "Slow", mar: "हळू" },
  { eng: "Hot", mar: "गरम" },
  { eng: "Cold", mar: "थंड" },
  { eng: "Warm", mar: "कोमट" },
  { eng: "Cool", mar: "थंडावा" },
  { eng: "Light", mar: "प्रकाश" },
  { eng: "Dark", mar: "अंधार" },
  { eng: "Open", mar: "उघडे" },
  { eng: "Closed", mar: "बंद" },
  { eng: "Start", mar: "सुरुवात" },
  { eng: "End", mar: "शेवट" },
  { eng: "Begin", mar: "सुरू करणे" },
  { eng: "Finish", mar: "पूर्ण करणे" },
  { eng: "Win", mar: "जिंकणे" },
  { eng: "Lose", mar: "हरणे" },
  { eng: "Try", mar: "प्रयत्न" },
  { eng: "Success", mar: "यश" },
  { eng: "Failure", mar: "अपयश" },
  { eng: "Hope", mar: "आशा" },
  { eng: "Fear", mar: "भीती" },
  { eng: "Love", mar: "प्रेम" },
  { eng: "Care", mar: "काळजी" },
  { eng: "Help", mar: "मदत" },
  { eng: "Share", mar: "वाटणे" },
  { eng: "Give", mar: "देणे" },
  { eng: "Take", mar: "घेणे" },
  { eng: "Keep", mar: "ठेवणे" },
  { eng: "Use", mar: "वापर" },
  { eng: "Make", mar: "बनवणे" },
  { eng: "Do", mar: "करणे" }
];